### ISSUE TITLE
Hide message history for suicidal person, mute offending people

### ISSUE THREAD

**Issue by upintheairsheep** [9021007/Suicide-Prevention-Bot#51]
1. For someone who talks about killing themselves, they temporarily lose the ability to see the channel’s message history
2. For people who encourage suicide, mute them, and possibly prevent them from messaging the other user.

**Comment by Killerjet101** [comment]
1. For anyone that is suicidal, cutting them out is probably the worse way to go about the situation. It's probably better if we added a system to notify staff of a suicide problem for human input to resolve the issue or have them instead reach out for help and get help with ways we already give them. BUT that will be a big issue with our privacy policy as we don't want anyone to worry about others knowing what you are going threw without consent or knowledge of that info being shared.

2. This would be a good idea to add but other bots or even Discord's own auto-mod system and do just that. Sure we could add it in the future but as of right now, it doesn't go with our future view/plan of giving everyone help. Then again that's all up to the big boss if we want to shift views.

**Comment by bubby932** [comment]
one thing - you can't prevent DMs as a bot
it's just not possible

**Comment by Killerjet101** [comment]
That as well, bots don't have that much freedom otherwise Discord would be hell
